var cam_width = camera_get_view_width(view_camera[0]);
var cam_height = camera_get_view_height(view_camera[0]);
var cam_x = camera_get_view_x(view_camera[0]);
var cam_y = camera_get_view_y(view_camera[0]);
depth = -25;
sucrose_lighting = false;
sucrose_color = 7490854;
sucrose_color_array = [327, 171, 435, 353, 555, 118, 508, 308];
dance_lighting = false;
dance_palette = 0;
sucrose_surface = surface_create(cam_width, cam_height);
surface_set_target(sucrose_surface);
draw_clear_alpha(0, 0);
surface_reset_target();
dance_surface = surface_create(cam_width, cam_height);
surface_set_target(dance_surface);
draw_clear_alpha(0, 0);
surface_reset_target();
boss_surface = surface_create(cam_width, cam_height);
surface_set_target(boss_surface);
draw_clear_alpha(0, 0);
surface_reset_target();
boss_radius = 120;
radius_increase = 0;
